export const PATHS = {
    SIGNIN: '/signin',
    SIGNUP: '/signup',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    EmailVerify: '/api/email/verify/:id/:hash',
    ResetPassword: '/api/reset-password',
    Categories: '/categories',
    AddCategories: '/addcategory',
    showCategory: '/categoryshow/:id',
    Advertise: '/Advertise/',
    AddAdvertise: '/addadvertise/',
    showAdvertise: '/advertise/:id',
    updateAdvertise: '/advertise/update/:id',
    adsByCategory: '/advertise/category/:id',
}