export const PATHS = {
    SIGNIN: '/signin',
    SIGNUP: '/signup',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    PROFILEUpdate: '/profile/update',
    EmailVerify: '/api/email/verify/:id/:hash',
    ResetPassword: '/api/reset-password',
    Categories: '/categories',
    AddCategories: '/addcategory',
    showCategory: '/categoryshow/:id',
    Advertise: '/Advertise/',
    AddAdvertise: '/addadvertise/',
    MYADVERTISES: '/myadvertises/:id',
    showAdvertise: '/advertise/:id',
    updateAdvertise: '/advertise/update/:id',
    adsByCategory: '/advertise/category/:id',
    ManageAds: '/advertisesRequests',
    Stats: '/stats',
    StatsHome: '/stats/home',
    Users: '/users',
    LISTFAVORIT: '/favoritlist/:id',
    LISTCOMMENTS: '/comment/:id',
    ALLNOTIFICATIONS: '/notifications/:id',

    NOtAUTHORIZED : '/notauthorized',
    USERDETAILS : '/user/details/:id'
}